### ISSUE TITLE
Export Channel ID link's to browser

### ISSUE THREAD

**Issue by girlvibe** [genki-ai/Discord-Data-Package-Parser#11]
One thing I noticed that really bothered me. I wanna be able to open direct messages of people I no longer speak to or have unadded. They get buried under all my new messages & it would be awesome if there was a way to open the actual channel. I've tried to do this but it takes a lot of time. I noticed that within this application I'm not even able to copy the selected channel ID. It's also a bit upsetting that I can't copy their username and #. Sometimes users have strange text characters within their name & it's a bit hard to search for them without copying their name and pasting it. Maybe you could have a way to right click and open the channel link into discord. THIS WOULD BE A PERFECT ADDITION. This could work for direct message groups & server channels too.

**Comment by genki-ai** [comment]
That would be a really good feature, I will add this in the next commit
