### ISSUE TITLE
Viewing DMs (probably some other messages too) that have over 2k messages is impossible

### ISSUE THREAD

**Issue by Taskmaster789** [genki-ai/Discord-Data-Package-Parser#14]
You probably already know of this issue

Opening a dm that has 1k messages and scrolling the messages is very choppy and slow

When I opened the dms with my significant other (about 50k messages) the whole program does the "the program is not responding" bit for a couple of mins then then is fine, and then I interact with the program, click or doing anything, in freezes up again

As this is this the only program that seems to make the discord data package messages readable, 
Do you plan to update the programs ability process greater number of messages?

**Comment by genki-ai** [comment]
heya, yes i do. when i originally wrote this i did not consider bigger conversations as it will load the full conversation into memory which can be taxing on most PCs. 
I do plan on resolving this in my next version by limiting how much is loaded at once.
