### ISSUE TITLE
Possiblity of an "export links" function?

### ISSUE THREAD

**Issue by CrumpThePenguin** [genki-ai/Discord-Data-Package-Parser#9]
It's really tedious copy/pasting every link as I find it. I'm looking for something specific so it would be really useful if there was a function to just find every link with http/https at the beginning and export it to a .txt to be later used in something like JDownloader.

**Comment by genki-ai** [comment]
I will be working on this again soon, and this is one of my planned features. I'll be sure to prioritize this first as this has been a common request.
